#!/bin/sh
# Generate tmp/math-fonts.tex: load TeX Live's math fonts by absolute
# file path instead of by name.
#
# Why: on macOS, XeTeX resolves font names through the system Core Text
# registry rather than fontconfig, and TeX Live's math fonts are not
# registered there. Loading them by absolute path (discovered via
# kpsewhich) makes the build work without modifying the system font
# registry. This also works on Windows / Linux TeX Live, so `make pdf`
# is universally correct.
set -e

OUT="$1"

TEXGYRE=$(kpsewhich texgyretermes-math.otf)
STIX=$(kpsewhich STIXTwoMath-Regular.otf)
LM=$(kpsewhich latinmodern-math.otf)
ASANA=$(kpsewhich Asana-Math.otf)

if [ -z "$TEXGYRE" ] || [ -z "$STIX" ] || [ -z "$LM" ] || [ -z "$ASANA" ]; then
    echo "texlive-font-paths: cannot locate TeX Live math fonts via kpsewhich" >&2
    echo "texlive-font-paths: is TeX Live installed and on PATH?" >&2
    exit 1
fi

# Split each full path into a directory (with trailing slash) and a filename,
# since unicode-math loads fonts via Path=/dir/,Extension=.otf {file}.
tg_dir=$(dirname "$TEXGYRE")/
tg_file=$(basename "$TEXGYRE")
stix_dir=$(dirname "$STIX")/
stix_file=$(basename "$STIX")
lm_dir=$(dirname "$LM")/
lm_file=$(basename "$LM")
asana_dir=$(dirname "$ASANA")/
asana_file=$(basename "$ASANA")

mkdir -p "$(dirname "$OUT")"

{
    printf '%% Auto-generated by tools/texlive-font-paths.sh -- do not edit.\n'
    printf '%% Loads TeX Live math fonts by absolute path (see tools/texlive-font-paths.sh).\n'
    printf '\\setmathfont{%s}[Path=%s,Extension=.otf]\n' "$tg_file" "$tg_dir"
    printf '\\setmathfont{%s}[Path=%s,Extension=.otf,\n' "$stix_file" "$stix_dir"
    printf '    range = {up/{Greek,greek}, it/{Greek,greek}, bfup/{Greek,greek}, bfit/{Greek,greek}}\n'
    printf ']\n'
    printf '\\setmathfont{%s}[Path=%s,Extension=.otf,\n' "$lm_file" "$lm_dir"
    printf '    range = {\\sum, \\prod, \\coprod, \\int, \\iint, \\iiint, \\iiiint, \\oint, \\bigcup, \\bigcap, \\bigsqcup, \\bigvee, \\bigwedge, \\bigoplus, \\bigotimes, \\bigodot}\n'
    printf ']\n'
    printf '\\setmathfont{%s}[Path=%s,Extension=.otf,\n' "$asana_file" "$asana_dir"
    printf '    range = {\\varnothing}\n'
    printf ']\n'
} > "$OUT"

echo "texlive-font-paths: wrote $OUT"
